forbole/kastle

- .github/workflows/lint.yml
- .github/workflows/release-please.yml
---
Update the branch name in the GH action workflows.
---
---
project's
license terms
> fix: workflows branch

- contexts/WalletManagerContext.tsx
- package.json
---
---
---
project's
license terms
> hotfix: handle missing public keys

- contexts/WalletManagerContext.tsx
- package.json
> chore(main): revert hotfix

- contexts/WalletManagerContext.tsx
- package.json
---
---
---
project's
license terms
> fix: hotfix public keys handling in wallet manager

- components/account-management/ManageAccounts.tsx
- contexts/WalletManagerContext.tsx
- hooks/useTransactionEstimate.ts
---
---
---
project's
license terms
> fix: hotfix missing public keys handling

- .github/README.md
---
---
---
project's
license terms
> chore: add README.md

- api/background/utils.ts
---
This PR intends to fix `getCurrentAccount` logic of browser api.
---
project's
license terms
> fix(api): fix getCurrentAccount logic

- contexts/WalletManagerContext.tsx
---
---
---
project's
license terms
> fix: handle missing public keys

- components/screens/PreviewMode.tsx
- components/screens/Settings.tsx
- contexts/SettingsContext.tsx
- entrypoints/popup/router.tsx
---
---
---
project's
license terms
> feat: add preview mode setting

- lib/migrations/2.0.4.ts
- lib/migrations/migration.ts
---
This PR fixes empty lock timeout by migration.
---
---
project's
license terms
> fix: fix empty lock timeout by migration

- components/layouts/FullscreenLayout.tsx
- components/layouts/PopupLayout.tsx
- components/screens/Onboarding.tsx
- components/screens/SetupPassword.tsx
- components/screens/full-pages/ImportPrivateKey.tsx
- components/screens/full-pages/ImportRecoveryPhrase.tsx
- components/send/HotWalletSending.tsx
- components/send/LedgerSending.tsx
- contexts/PostHogWrapperProvider.tsx
- contexts/WalletManagerContext.tsx
- hooks/useAnalytics.ts
- hooks/useStorageState.ts
- package-lock.json
- package.json
---
---
---
project's
license terms
> feat: posthog integration

- contexts/SettingsContext.tsx
- lib/migrations/2.3.0.ts
- lib/migrations/migration.ts
---
Updating the mainnet RPC URL according to https://forbole.atlassian.net/browse/KW-140
---
---
project's
license terms
> chore: update mainnet RPC URL

- components/screens/SetupPassword.tsx
---
Just delay password validation according to https://forbole.atlassian.net/browse/KW-133
---
---
project's
license terms
> feat: delay password validation

- components/screens/Send.tsx
- components/send/DetailsStep.tsx
---
- Merging the address and amount step
- Added red borders to fields on error
---
---
project's
license terms
> style: merge destination address and amount

- components/LabelLoading.tsx
- components/dashboard/TokenListItem.tsx
- components/kas-asset/KasHistory.tsx
- components/kas-asset/KasInfo.tsx
- components/layouts/FullscreenLayout.tsx
- components/layouts/PopupLayout.tsx
- components/screens/Dashboard.tsx
- components/screens/KasAsset.tsx
- components/screens/TokenAsset.tsx
- components/screens/TokenOperation.tsx
- components/screens/full-pages/DeployToken.tsx
- components/screens/full-pages/MintToken.tsx
- components/screens/full-pages/account-management/ManageAccounts.tsx
- components/token-asset/TokenHistory.tsx
- components/token-asset/TokenHistoryItem.tsx
- components/token-asset/TokenInfo.tsx
- components/token-operation/ConfirmTokenOperationStep.tsx
- components/token-operation/HotWalletBroadcastTokenOperation.tsx
- contexts/WalletManagerContext.tsx
- entrypoints/popup/router.tsx
- hooks/useKasFyi.ts
- hooks/useKasplex.ts
- hooks/useOpListByAddressAndTicker.ts
- hooks/useTokenInfo.ts
- hooks/useTokenListByAddress.ts
- hooks/useTokenMetadata.ts
- lib/krc20.ts
- lib/utils.ts
- package-lock.json
- package.json
---
- Adds mint operation
- Adds token listing
- Adds token history
- Refactors some parts of KRC20 implementation 
---
---
project's
license terms
> feat: KRC20 mint, listing, history

- components/screens/full-pages/ImportRecoveryPhrase.tsx
- components/screens/full-pages/ShowRecoveryPhrase.tsx
---
Improves recovery phrase to have better color contract for numbering and padding.
---
---
project's
license terms
> feat(style): improve styles in recovery phrase components

- components/screens/full-pages/DeployToken.tsx
- components/screens/full-pages/MintToken.tsx
- components/send/DetailsStep.tsx
- components/token-operation/ConfirmTokenOperationStep.tsx
- components/token-operation/HotWalletBroadcastTokenOperation.tsx
- lib/forbole.ts
- lib/kaspa.ts
- lib/krc20.ts
---
---
---
project's
license terms
> feat(krc20): krc-20-forbole-fee

- components/screens/full-pages/account-management/AccountItem.tsx
---
This PR shrink address in manage accounts page.
---
---
project's
license terms
> feat(style): shrink address in manage accounts page

- components/screens/full-pages/ImportPrivateKey.tsx
---
---
---
project's
license terms
> style(ImportPrivateKey): update import private key color contrast

- contexts/WalletManagerContext.tsx
- package.json
---
This PR fixes the initialization bug of ledger wallet importing.
---
---
project's
license terms
> fix(ledger): initialize ledger last number

- components/screens/full-pages/account-management/ManageAccounts.tsx
---
---
---
project's
license terms
> fix(account-management): update header title for account import

- components/GeneralHeader.tsx
- components/screens/RemoveWallet.tsx
---
---
---
project's
license terms
> style: update remove wallet statment

- components/token-asset/TokenInfo.tsx
---
---
---
project's
license terms
> feat: update UI to indicate small percentage minted

- components/screens/full-pages/ConfirmMint.tsx
- components/screens/full-pages/MintToken.tsx
- components/screens/full-pages/MintingToken.tsx
- components/send/ConfirmStep.tsx
- components/send/LoadingStatus.tsx
- lib/wallet/account/hot-wallet-private-key.ts
---
---
---
project's
license terms
> style: adjust UI

- components/screens/full-pages/ConfirmMint.tsx
- components/screens/full-pages/MintToken.tsx
- components/screens/full-pages/MintingToken.tsx
---
---
---
project's
license terms
> style: update tooltip content in MintKRC20 pages

- components/screens/DevMode.tsx
- components/screens/KasAsset.tsx
- components/screens/Onboarding.tsx
- components/screens/RemoveWallet.tsx
- components/screens/ResetWallet.tsx
- components/screens/Settings.tsx
- components/screens/SetupPassword.tsx
- components/screens/TokenAsset.tsx
- components/screens/Welcome.tsx
- components/screens/full-pages/ShowRecoveryPhrase.tsx
- components/screens/full-pages/account-management/AccountItem.tsx
---
---
---
project's
license terms
> style: update colors

- components/send/LedgerSending.tsx
- lib/wallet/account/ledger-account.ts
---
This PR fixes the issue of ledger signing missing the account index.
---
---
project's
license terms
> fix: include account index in ledger transaction signing

- components/screens/Settings.tsx
---
---
---
project's
license terms
> style: replace dropdown with bottom sheet

- components/screens/full-pages/ImportPrivateKey.tsx
- components/screens/full-pages/ImportRecoveryPhrase.tsx
- components/screens/full-pages/ShowPrivateKey.tsx
- components/screens/full-pages/ShowRecoveryPhrase.tsx
- entrypoints/main.css
---
---
---
project's
license terms
> style: update credentials hiding method

- components/screens/Dashboard.tsx
- hooks/useTokenMetadata.ts
- hooks/useTotalBalance.ts
- lib/utils.ts
---
---
---
project's
license terms
> fix: include tokens in total balance

- components/layouts/FullscreenLayout.tsx
- components/screens/full-pages/WalletLockedAlert.tsx
- lib/auto-lock-manager.ts
- lib/keyring-manager.ts
- lib/service/handlers/keyring-lock.ts
---
---
---
project's
license terms
> fix: sync full page keyring status

- components/screens/full-pages/ledger/ImportLedger.tsx
- components/screens/full-pages/ledger/LedgerConnectForImport.tsx
- components/screens/full-pages/ledger/LedgerConnectForImportFailed.tsx
---
---
---
project's
license terms
> refactor: improve import ledger wallet flow

- components/layouts/FullscreenLayout.tsx
- components/onboarding/ChooseImport.tsx
- components/onboarding/OnboardingSuccess.tsx
- components/onboarding/SetupPassword.tsx
- components/onboarding/Welcome.tsx
- components/screens/Dashboard.tsx
- components/screens/Onboarding.tsx
- components/screens/RemoveWallet.tsx
- components/screens/ResetWallet.tsx
- components/screens/SetupPassword.tsx
- components/screens/Welcome.tsx
- components/screens/full-pages/AccountsImported.tsx
- components/screens/full-pages/ImportPrivateKey.tsx
- components/screens/full-pages/ImportRecoveryPhrase.tsx
- components/screens/full-pages/TokenOperationFailed.tsx
- components/screens/full-pages/TokenOperationSuccess.tsx
- components/screens/full-pages/account-management/ManageAccounts.tsx
- components/screens/full-pages/ledger/ImportLedger.tsx
- components/screens/full-pages/ledger/LedgerConnectForImport.tsx
- components/screens/full-pages/ledger/LedgerConnectForImportFailed.tsx
- entrypoints/popup/router.tsx
- hooks/useExtensionUtils.ts
- lib/service/extension-service.ts
- lib/service/handlers/reopenPopup.ts
- lib/utils.ts
---
---
---
project's
license terms
> feat: onboarding-rework

- components/layouts/PopupLayout.tsx
- components/screens/Dashboard.tsx
- components/screens/browser-api/ConnectConfirm.tsx
- components/screens/browser-api/SignAndBroadcastTxConfirm.tsx
- components/screens/browser-api/SignTxConfirm.tsx
- components/screens/browser-api/sign/SignConfirm.tsx
---
---
---
project's
license terms
> fix(ui): prevent layout from scrolling

- api/browser.ts
- components/screens/Settings.tsx
- components/screens/browser-api/ConnectConfirm.tsx
- components/screens/browser-api/sign/SignConfirm.tsx
- contexts/SettingsContext.tsx
- hooks/useTotalBalance.ts
- lib/forbole.ts
- lib/migrations/migration.ts
- lib/migrations/v2.10.1.ts
---
---
---
project's
license terms
> chore: remove testnet-11

- api/background/background-service.ts
- api/background/handlers/connect.ts
- api/background/handlers/getAccount.ts
- api/background/handlers/signAndBroadcastTx.ts
- api/background/handlers/signTx.ts
- api/background/utils.ts
- api/browser.ts
- api/extension.ts
- api/message.ts
- components/screens/browser-api/ConnectConfirm.tsx
- components/screens/browser-api/SignAndBroadcastTxConfirm.tsx
- components/screens/browser-api/SignTxConfirm.tsx
- components/screens/browser-api/sign-and-broadcast/LedgerSignAndBroadcast.tsx
- components/screens/browser-api/sign-and-broadcast/SignAndBroadcast.tsx
- components/screens/browser-api/sign-tx/LedgerSignTx.tsx
- components/screens/browser-api/sign-tx/SignTx.tsx
- entrypoints/content.ts
- hooks/useTotalBalance.ts
- package-lock.json
- package.json
---
---
---
project's
license terms
> refactor(browser-api): apply zod for browser api

- api/background/utils.ts
- api/content-script/listeners/ethereum/accountsChanged.ts
…ng for listener
---
---
---
project's
license terms
> refactor(api): improve accountsChanged event listener

- components/screens/Dashboard.tsx
---
---
---
project's
license terms
> style: prevent skeleton from overlapping warning message

- components/screens/browser-api/sign-and-broadcast/Broadcasting.tsx
- components/send/Broadcasting.tsx
---
---
---
project's
license terms
> style: update wording

- components/dashboard/TokenListItem.tsx
- components/send/TickerSelect.tsx
- components/send/TickerSelectItem.tsx
- contexts/SettingsContext.tsx
- hooks/usePortfolioPerformance.ts
- hooks/useTokenListByAddress.ts
---
---
---
project's
license terms
> fix: misc bugs

- components/send/DetailsStep.tsx
---
---
---
project's
license terms
> style: remove KAS from the title of send page

- components/SettingItem.tsx
- components/dashboard/KNS.tsx
- components/dashboard/KRC721List.tsx
- components/screens/Settings.tsx
- components/screens/full-pages/MintToken.tsx
- components/send/DetailsStep.tsx
- components/settings/CurrencySelection.tsx
---
---
---
project's
license terms
> style: fix uats for uis

- api/content-script/listeners/settings-updated.ts
- api/content-script/listeners/wallet-settings-updated.ts
- api/ethereum.ts
---
This PR intends to make `kas:account_changed` event to return address so that the sdk can easily change the watching address without any other operations:
https://github.com/forbole/kastle-sdk/blob/chore/improve-sdk/packages/sdk/src/listener.ts#L16
---
---
project's
license terms
> fix(api): return address for account changed event

- api/background/utils.ts
- api/content-script/listeners/settings-updated.ts
- api/content-script/listeners/wallet-settings-updated.ts
- components/screens/browser-api/kaspa/SwitchKaspaNetwork.tsx
- docs/index.js
- lib/wallet/account/hot-wallet-account.ts
- lib/wallet/account/hot-wallet-private-key.ts
- lib/wallet/wallet-interface.ts
---
This PR introduces `kas:host_connected` event to make sdk be able to listen connected event easilier.
---
---
project's
license terms
> feat(browser-api): add host connected event

- api/background/handlers/ethereum/signTypedDataV4.ts
- components/screens/browser-api/ethereum/EthereumSignTypedDataV4.tsx
- components/screens/browser-api/ethereum/sign-typed-data/HotWalletTypedDataV4.tsx
- components/screens/browser-api/ethereum/sign-typed-data/SignTypedDataV4.tsx
- entrypoints/popup/router.tsx
---
---
---
project's
license terms
> feat(api): add eth sign typed data v4 method

- components/kns-transfer/KNSTransferDetails.tsx
- components/krc-721-transfer/KRC721TransferDetails.tsx
- components/send/DetailsStep.tsx
---
---
---
project's
license terms
> fix: fix non selectable items

- components/dashboard/KNS.tsx
- components/dashboard/KNSText.tsx
- components/dashboard/KNSTextItem.tsx
- components/kns-transfer/KNSTransferBroadcast.tsx
- components/kns-transfer/KNSTransferConfirm.tsx
- components/kns-transfer/KNSTransferDetails.tsx
- components/kns-transfer/KNSTransferFailure.tsx
- components/receive/KNSMenu.tsx
- components/screens/Dashboard.tsx
- components/screens/KNSAsset.tsx
- components/screens/KNSTextAsset.tsx
- components/screens/KNSTransfer.tsx
- entrypoints/popup/router.tsx
- hooks/useKns.ts
- lib/kns.ts
---
https://forbole.atlassian.net/browse/KW-280
---
---
project's
license terms
> feat: support for KNS text inscription

- api/background/handlers/ethereum/publicClient.ts
- api/background/handlers/ethereum/request.ts
---
---
---
project's
license terms
> feat(api): support ethereum public client methods

- api/content-script/listeners/ethereum/accountsChanged.ts
- lib/ethereum/wallet/account-factory.ts
---
---
---
project's
license terms
> fix(ethereum-api): fix wallet account methods

- api/background/handlers/ethereum/accounts.ts
- api/background/handlers/ethereum/utils.ts
…nlocked check for eth_accounts response
---
---
---
project's
license terms
> fix(api): ensure address comparison is case-insensitive and remove unlock check for eth_accounts

- contexts/SettingsContext.tsx
---
Fix https://forbole.atlassian.net/browse/KW-318
---
---
project's
license terms
> chore: update RPC URLs

- components/screens/full-pages/ledger/LedgerManageAccounts.tsx
---
---
---
project's
license terms
> fix: fix ledger manage account process

- api/background/handlers/ethereum/switchNetwork.ts
- components/screens/browser-api/ethereum/SwitchEthereumNetwork.tsx
- components/screens/browser-api/ethereum/send-transaction/SendTransaction.tsx
- lib/layer2.ts
---
---
---
project's
license terms
> feat: support kasplex l2

- hooks/kasplex/useTokenMetadata.ts
---
---
---
project's
license terms
> fix: update base URL in useTokenMetadata handler

- api/background/handlers/ethereum/publicClient.ts
---
---
---
project's
license terms
> feat(evm-api): implement chain selection for public client

- components/screens/ChangePassword.tsx
- components/screens/WalletUnlock.tsx
- lib/keyring-manager.ts
- package-lock.json
- package.json
> Revert "feat: migrate key derivation to Argon2id for improved security and performance"

- components/screens/ChangePassword.tsx
- components/screens/WalletUnlock.tsx
- lib/keyring-manager.ts
- package-lock.json
- package.json
> Revert "Revert "feat: migrate key derivation to Argon2id for improved security and performance""

- components/screens/browser-api/kaspa/SignMessageConfirm.tsx
- components/screens/browser-api/kaspa/sign-message/SignMessage.tsx
---
---
---
project's
license terms
> fix(ui): make sign message ui scrollable

- components/screens/browser-api/ConnectConfirm.tsx
- components/screens/browser-api/kaspa/sign-message/SignMessage.tsx
---
---
---
project's
license terms
> feat(ui): improve UI for sign message and connect api

- components/screens/KRC721.tsx
---
---
---
project's
license terms
> feat(ui): add empty content for nft without attributes

- components/krc20-asset/TokenInfo.tsx
---
---
---
project's
license terms
> chore: improve krc20 assets network showing

- components/screens/asset-selector/Erc20SelectItem.tsx
- components/screens/asset-selector/EvmKasSelectItem.tsx
- components/screens/asset-selector/Krc20SelectItem.tsx
---
---
---
project's
license terms
> fix(ui): fix select asset image

- components/dashboard/AddressItem.tsx
- components/dashboard/ClipboardCopy.tsx
- components/screens/browser-api/ConnectConfirm.tsx
- components/screens/receive-addresses/AddressItem.tsx
- components/screens/receive-addresses/ReceiveAddress.tsx
---
---
---
project's
license terms
> feat: add evm address to connect

- api/background/handlers/ethereum/signMessage.ts
- components/screens/browser-api/ethereum/EthereumSignMessageConfirm.tsx
- components/screens/browser-api/ethereum/sign-message/HotWalletSignMessage.tsx
- components/screens/browser-api/ethereum/sign-message/SignMessage.tsx
- lib/ethereum/wallet/account/private-key-account.ts
---
---
---
project's
license terms
> fix(api): fix evm sign message api

- components/screens/Erc20Asset.tsx
- components/send/evm/erc20-send/Erc20Send.tsx
- hooks/evm/useErc20Assets.ts
- hooks/evm/useErc20Info.ts
- hooks/evm/useErc20InfoFromApi.ts
- hooks/evm/useErc20TokensFromApi.ts
- lib/layer2.ts
---
---
---
project's
license terms
> feat: integrate explorer api for erc20
